version: '3.8'

services:
  app:
    build: .
      context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
